[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.85"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.6", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.10.3", features = ["tray-icon", "image-png"] }
tauri-plugin-log = "2"
tauri-plugin-global-shortcut = "2.3.1"
tauri-plugin-clipboard-manager = "2.3.2"
cpal = "0.17.1"
hound = "3.5.1"
core-foundation = "0.10.1"
tokio = { version = "1.50.0", features = ["full"] }
core-graphics = "0.25.0"
core-graphics-types = "0.2.0"
whisper-rs = { version = "0.16.0", features = ["metal"] }
llama-cpp-2 = { git = "https://github.com/utilityai/llama-cpp-rs.git", features = ["metal"] }
encoding_rs = "0.8"
dirs = "6.0.0"
